### ISSUE TITLE
account_storno balance = 0

### ISSUE THREAD

**Issue by ploegvde** [feketemihai/l10n-romania#83]
Hello,

I have tested the account_storno module and i'm sure that this module can also be used in the Netherlands. I tested it and all works fine. The only thing is, that i see that on a created refund invoice the balance is always zero. And if the balance of an invoice is zero, then this invoice can't be reconciled on the bank statement.

Is the balance=0 a bug or do i see this wrongly?

**Comment by feketemihai** [comment]
Hi, the ideea of storno is to use the same facility...so the in_refund, out_refund invoices doesn't work because storno means a in_invoice or out_invoice with minus quantity or price, that gives you minus balance and you can reconcile...i will test the day after tomorow reconciliation from bank, cash...but as far as i know it's working.

Keep you posted.

Mihai Fekete
Sent from Samsung Mobile.

-------- Original message --------
From: Erwin van der Ploeg
Date:24/03/2015 21:06 (GMT+02:00)
To: odoo-romania/l10n-romania
Subject: [l10n-romania] account_storno balance = 0 (#83)

Hello,

I have tested the account_storno module and i'm sure that this module can also be used in the Netherlands. I tested it and all works fine. The only thing is, that i see that on a created refund invoice the balance is always zero. And if the balance of an invoice is zero, then this invoice can't be reconciled on the bank statement.

Is the balance=0 a bug or do i see this wrongly?

##

**Comment by ploegvde** [comment]
Hi, i checked (V8). When i create just a invoice with a minus qty the balance of this validated invoice is zero. When i create a refund invoice trough the Button "Refund invoice" on a normal debit invoice. The refund invoice is made in normal sale journal (correct) with a minus qty (als correct). But on validating the balance is zero.

This leads in a wrong balance total on the invoice list and problems on reconcile, while reconcile is done on the balance (if i'm not mistaken).

If you have some time to check, would be great.

**Comment by feketemihai** [comment]
Ok...now i remember that i'm using a other branch where a reqrite the amount_residual function on the invoice to allow negative balance, by default it's checking to be positive or zero...i will add the function to the storno module...

**Comment by feketemihai** [comment]
Could you try this branch: 

https://github.com/feketemihai/l10n-romania/tree/fix_storno_invoice_residual

**Comment by feketemihai** [comment]
Also, i short notice, from next week since the project from Romania has been accepted to the OCA, this modules will be proposed to OCA general branches...

**Comment by ploegvde** [comment]
Hi, this branch https://github.com/feketemihai/l10n-romania/tree/fix_storno_invoice_residual gives a balance! This one looks ok.

I saw that this module is going to be pushed to OCA. Good!

I will test some more! Thanks for the quick response and help!

**Comment by feketemihai** [comment]
Your welcome...hopefully next week i will make a pr for the storno module in the OCA...

**Comment by ploegvde** [comment]
Thanks, one last question. Is there also a V7 version?

**Comment by feketemihai** [comment]
No, but i will propose to OCA, i will do it also on V7...if it's ok for you...

**Comment by ploegvde** [comment]
Would be perfect!

**Comment by feketemihai** [comment]
Hi @erwin-bas-solutions You can find the storno module for v7 at 
https://github.com/feketemihai/account-financial-tools/tree/7.0
I will have to review it, add tests, translation and propose it to OCA.

**Comment by ploegvde** [comment]
Thanks! I will have a look
